//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Dummy.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitStockEntityMappings();
			InitStockSectorEntityMappings();
		}

		/// <summary>Inits StockEntity's mappings</summary>
		private void InitStockEntityMappings()
		{
			this.AddElementMapping("StockEntity", @"Dummy", @"dbo", "Stock", 6, 0);
			this.AddElementFieldMapping("StockEntity", "Code", "Code", false, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("StockEntity", "CreatedDate", "CreatedDate", false, "DateTime2", 0, 7, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("StockEntity", "Name", "Name", false, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("StockEntity", "StockId", "StockId", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 3);
			this.AddElementFieldMapping("StockEntity", "StockSectorId", "StockSectorId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 4);
			this.AddElementFieldMapping("StockEntity", "UpdateDate", "UpdateDate", false, "DateTime2", 0, 7, 0, false, "", null, typeof(System.DateTime), 5);
		}

		/// <summary>Inits StockSectorEntity's mappings</summary>
		private void InitStockSectorEntityMappings()
		{
			this.AddElementMapping("StockSectorEntity", @"Dummy", @"dbo", "StockSector", 5, 0);
			this.AddElementFieldMapping("StockSectorEntity", "Code", "Code", false, "NVarChar", 50, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("StockSectorEntity", "CreateDate", "CreateDate", false, "DateTime2", 0, 7, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("StockSectorEntity", "Name", "Name", false, "NVarChar", 100, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("StockSectorEntity", "StockSectorId", "StockSectorId", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 3);
			this.AddElementFieldMapping("StockSectorEntity", "UpdateDate", "UpdateDate", false, "DateTime2", 0, 7, 0, false, "", null, typeof(System.DateTime), 4);
		}

	}
}
