//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Dummy.HelperClasses
{
	/// <summary>Field Creation Class for entity StockEntity</summary>
	public partial class StockFields
	{
		/// <summary>Creates a new StockEntity.Code field instance</summary>
		public static EntityField2 Code { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockFieldIndex.Code); }}
		/// <summary>Creates a new StockEntity.CreatedDate field instance</summary>
		public static EntityField2 CreatedDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockFieldIndex.CreatedDate); }}
		/// <summary>Creates a new StockEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockFieldIndex.Name); }}
		/// <summary>Creates a new StockEntity.StockId field instance</summary>
		public static EntityField2 StockId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockFieldIndex.StockId); }}
		/// <summary>Creates a new StockEntity.StockSectorId field instance</summary>
		public static EntityField2 StockSectorId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockFieldIndex.StockSectorId); }}
		/// <summary>Creates a new StockEntity.UpdateDate field instance</summary>
		public static EntityField2 UpdateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockFieldIndex.UpdateDate); }}
	}

	/// <summary>Field Creation Class for entity StockSectorEntity</summary>
	public partial class StockSectorFields
	{
		/// <summary>Creates a new StockSectorEntity.Code field instance</summary>
		public static EntityField2 Code { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockSectorFieldIndex.Code); }}
		/// <summary>Creates a new StockSectorEntity.CreateDate field instance</summary>
		public static EntityField2 CreateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockSectorFieldIndex.CreateDate); }}
		/// <summary>Creates a new StockSectorEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockSectorFieldIndex.Name); }}
		/// <summary>Creates a new StockSectorEntity.StockSectorId field instance</summary>
		public static EntityField2 StockSectorId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockSectorFieldIndex.StockSectorId); }}
		/// <summary>Creates a new StockSectorEntity.UpdateDate field instance</summary>
		public static EntityField2 UpdateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockSectorFieldIndex.UpdateDate); }}
	}
	

}