//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using Dummy.FactoryClasses;
using Dummy.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Dummy.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitStockEntityInfo();
			InitStockSectorEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits StockEntity's info objects</summary>
		private void InitStockEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(StockFieldIndex), "StockEntity");
			this.AddElementFieldInfo("StockEntity", "Code", typeof(System.String), false, false, false, false,  (int)StockFieldIndex.Code, 2147483647, 0, 0);
			this.AddElementFieldInfo("StockEntity", "CreatedDate", typeof(System.DateTime), false, false, false, false,  (int)StockFieldIndex.CreatedDate, 0, 0, 7);
			this.AddElementFieldInfo("StockEntity", "Name", typeof(System.String), false, false, false, false,  (int)StockFieldIndex.Name, 2147483647, 0, 0);
			this.AddElementFieldInfo("StockEntity", "StockId", typeof(System.Int32), true, false, true, false,  (int)StockFieldIndex.StockId, 0, 0, 10);
			this.AddElementFieldInfo("StockEntity", "StockSectorId", typeof(System.Int32), false, true, false, false,  (int)StockFieldIndex.StockSectorId, 0, 0, 10);
			this.AddElementFieldInfo("StockEntity", "UpdateDate", typeof(System.DateTime), false, false, false, false,  (int)StockFieldIndex.UpdateDate, 0, 0, 7);
		}

		/// <summary>Inits StockSectorEntity's info objects</summary>
		private void InitStockSectorEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(StockSectorFieldIndex), "StockSectorEntity");
			this.AddElementFieldInfo("StockSectorEntity", "Code", typeof(System.String), false, false, false, false,  (int)StockSectorFieldIndex.Code, 50, 0, 0);
			this.AddElementFieldInfo("StockSectorEntity", "CreateDate", typeof(System.DateTime), false, false, false, false,  (int)StockSectorFieldIndex.CreateDate, 0, 0, 7);
			this.AddElementFieldInfo("StockSectorEntity", "Name", typeof(System.String), false, false, false, false,  (int)StockSectorFieldIndex.Name, 100, 0, 0);
			this.AddElementFieldInfo("StockSectorEntity", "StockSectorId", typeof(System.Int32), true, false, true, false,  (int)StockSectorFieldIndex.StockSectorId, 0, 0, 10);
			this.AddElementFieldInfo("StockSectorEntity", "UpdateDate", typeof(System.DateTime), false, false, false, false,  (int)StockSectorFieldIndex.UpdateDate, 0, 0, 7);
		}
	}
}