//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Dummy.HelperClasses;
using Dummy.FactoryClasses;
using Dummy.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Dummy.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Configuration'.<br/><br/></summary>
	[Serializable]
	public partial class ConfigurationEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static ConfigurationEntityStaticMetaData _staticMetaData = new ConfigurationEntityStaticMetaData();
		private static ConfigurationRelations _relationsFactory = new ConfigurationRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ConfigurationEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ConfigurationEntityStaticMetaData()
			{
				SetEntityCoreInfo("ConfigurationEntity", InheritanceHierarchyType.None, false, (int)Dummy.EntityType.ConfigurationEntity, typeof(ConfigurationEntity), typeof(ConfigurationEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static ConfigurationEntity()
		{
		}

		/// <summary> CTor</summary>
		public ConfigurationEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ConfigurationEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ConfigurationEntity</param>
		public ConfigurationEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="configurationId">PK value for Configuration which data should be fetched into this Configuration object</param>
		public ConfigurationEntity(System.Int32 configurationId) : this(configurationId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="configurationId">PK value for Configuration which data should be fetched into this Configuration object</param>
		/// <param name="validator">The custom validator object for this ConfigurationEntity</param>
		public ConfigurationEntity(System.Int32 configurationId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.ConfigurationId = configurationId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ConfigurationEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ConfigurationEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ConfigurationRelations Relations { get { return _relationsFactory; } }

		/// <summary>The ConfigurationId property of the Entity Configuration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Configuration"."ConfigurationId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 ConfigurationId
		{
			get { return (System.Int32)GetValue((int)ConfigurationFieldIndex.ConfigurationId, true); }
			set { SetValue((int)ConfigurationFieldIndex.ConfigurationId, value); }		}

		/// <summary>The CreateDate property of the Entity Configuration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Configuration"."CreateDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime2, 7, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreateDate
		{
			get { return (System.DateTime)GetValue((int)ConfigurationFieldIndex.CreateDate, true); }
			set	{ SetValue((int)ConfigurationFieldIndex.CreateDate, value); }
		}

		/// <summary>The Name property of the Entity Configuration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Configuration"."Name".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)ConfigurationFieldIndex.Name, true); }
			set	{ SetValue((int)ConfigurationFieldIndex.Name, value); }
		}

		/// <summary>The UpdateDate property of the Entity Configuration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Configuration"."UpdateDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime2, 7, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime UpdateDate
		{
			get { return (System.DateTime)GetValue((int)ConfigurationFieldIndex.UpdateDate, true); }
			set	{ SetValue((int)ConfigurationFieldIndex.UpdateDate, value); }
		}

		/// <summary>The Value property of the Entity Configuration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Configuration"."Value".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Value
		{
			get { return (System.String)GetValue((int)ConfigurationFieldIndex.Value, true); }
			set	{ SetValue((int)ConfigurationFieldIndex.Value, value); }
		}

		/// <summary>The Version property of the Entity Configuration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Configuration"."Version".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 Version
		{
			get { return (System.Int32)GetValue((int)ConfigurationFieldIndex.Version, true); }
			set	{ SetValue((int)ConfigurationFieldIndex.Version, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace Dummy
{
	public enum ConfigurationFieldIndex
	{
		///<summary>ConfigurationId. </summary>
		ConfigurationId,
		///<summary>CreateDate. </summary>
		CreateDate,
		///<summary>Name. </summary>
		Name,
		///<summary>UpdateDate. </summary>
		UpdateDate,
		///<summary>Value. </summary>
		Value,
		///<summary>Version. </summary>
		Version,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Dummy.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Configuration. </summary>
	public partial class ConfigurationRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticConfigurationRelations
	{

		/// <summary>CTor</summary>
		static StaticConfigurationRelations() { }
	}
}
