//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace Dummy.TypedListClasses
{
	/// <summary>Class which represents a row in the typed list 'Dbo.StockTypedList'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the method <see cref="Dummy.FactoryClasses.QueryFactory.GetStockTypedListTypedList"/>.
	/// Contains the following entity definition(s):
	/// Entity: Dbo.Stock. <br/>
	/// Entity: Dbo.StockSector. <br/>
	/// </remarks>
	[Serializable]
	public partial class StockTypedListRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="StockTypedListRow"/> class.</summary>
		public StockTypedListRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the StockId field. Mapped onto 'Dbo.Stock.StockId'</summary>
		public System.Int32 StockId { get; set; }
		/// <summary>Gets or sets the Code field. Mapped onto 'Dbo.Stock.Code'</summary>
		public System.String Code { get; set; }
		/// <summary>Gets or sets the Name field. Mapped onto 'Dbo.Stock.Name'</summary>
		public System.String Name { get; set; }
		/// <summary>Gets or sets the StockSectorId field. Mapped onto 'Dbo.Stock.StockSectorId'</summary>
		public System.Int32 StockSectorId { get; set; }
		/// <summary>Gets or sets the Code1 field. Mapped onto 'Dbo.StockSector.Code'</summary>
		public System.String Code1 { get; set; }
		/// <summary>Gets or sets the Name1 field. Mapped onto 'Dbo.StockSector.Name'</summary>
		public System.String Name1 { get; set; }
	}
}

