//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace Dummy
{

	/// <summary>Index enum to fast-access TypedList Fields in the Columns collection of the Typed List: StockTypedList</summary>
	public enum StockTypedListTypedListFieldIndex
	{
		///<summary>StockId</summary>
		StockId,
		///<summary>Code</summary>
		Code,
		///<summary>Name</summary>
		Name,
		///<summary>StockSectorId</summary>
		StockSectorId,
		///<summary>Code1</summary>
		Code1,
		///<summary>Name1</summary>
		Name1,
		/// <summary></summary>
		AmountOfFields
	}

	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>Configuration</summary>
		ConfigurationEntity,
		///<summary>OrderHistory</summary>
		OrderHistoryEntity,
		///<summary>OrderType</summary>
		OrderTypeEntity,
		///<summary>Portofolio</summary>
		PortofolioEntity,
		///<summary>PortofolioItem</summary>
		PortofolioItemEntity,
		///<summary>Stock</summary>
		StockEntity,
		///<summary>StockSector</summary>
		StockSectorEntity,
		///<summary>Summary</summary>
		SummaryEntity,
		///<summary>Transaction</summary>
		TransactionEntity,
		///<summary>TransactionStatus</summary>
		TransactionStatusEntity,
		///<summary>TransactionType</summary>
		TransactionTypeEntity,
		///<summary>User</summary>
		UserEntity
	}



	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END

}

