//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Dummy.HelperClasses
{
	/// <summary>Field Creation Class for entity ConfigurationEntity</summary>
	public partial class ConfigurationFields
	{
		/// <summary>Creates a new ConfigurationEntity.ConfigurationId field instance</summary>
		public static EntityField2 ConfigurationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ConfigurationFieldIndex.ConfigurationId); }}
		/// <summary>Creates a new ConfigurationEntity.CreateDate field instance</summary>
		public static EntityField2 CreateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ConfigurationFieldIndex.CreateDate); }}
		/// <summary>Creates a new ConfigurationEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ConfigurationFieldIndex.Name); }}
		/// <summary>Creates a new ConfigurationEntity.UpdateDate field instance</summary>
		public static EntityField2 UpdateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ConfigurationFieldIndex.UpdateDate); }}
		/// <summary>Creates a new ConfigurationEntity.Value field instance</summary>
		public static EntityField2 Value { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ConfigurationFieldIndex.Value); }}
		/// <summary>Creates a new ConfigurationEntity.Version field instance</summary>
		public static EntityField2 Version { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ConfigurationFieldIndex.Version); }}
	}

	/// <summary>Field Creation Class for entity OrderHistoryEntity</summary>
	public partial class OrderHistoryFields
	{
		/// <summary>Creates a new OrderHistoryEntity.Amount field instance</summary>
		public static EntityField2 Amount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderHistoryFieldIndex.Amount); }}
		/// <summary>Creates a new OrderHistoryEntity.CancelDate field instance</summary>
		public static EntityField2 CancelDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderHistoryFieldIndex.CancelDate); }}
		/// <summary>Creates a new OrderHistoryEntity.CreateDate field instance</summary>
		public static EntityField2 CreateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderHistoryFieldIndex.CreateDate); }}
		/// <summary>Creates a new OrderHistoryEntity.OrderDate field instance</summary>
		public static EntityField2 OrderDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderHistoryFieldIndex.OrderDate); }}
		/// <summary>Creates a new OrderHistoryEntity.OrderHistoryId field instance</summary>
		public static EntityField2 OrderHistoryId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderHistoryFieldIndex.OrderHistoryId); }}
		/// <summary>Creates a new OrderHistoryEntity.OrderTypeId field instance</summary>
		public static EntityField2 OrderTypeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderHistoryFieldIndex.OrderTypeId); }}
		/// <summary>Creates a new OrderHistoryEntity.UpdateDate field instance</summary>
		public static EntityField2 UpdateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderHistoryFieldIndex.UpdateDate); }}
	}

	/// <summary>Field Creation Class for entity OrderTypeEntity</summary>
	public partial class OrderTypeFields
	{
		/// <summary>Creates a new OrderTypeEntity.Code field instance</summary>
		public static EntityField2 Code { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderTypeFieldIndex.Code); }}
		/// <summary>Creates a new OrderTypeEntity.CreateDate field instance</summary>
		public static EntityField2 CreateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderTypeFieldIndex.CreateDate); }}
		/// <summary>Creates a new OrderTypeEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderTypeFieldIndex.Name); }}
		/// <summary>Creates a new OrderTypeEntity.OrderTypeId field instance</summary>
		public static EntityField2 OrderTypeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderTypeFieldIndex.OrderTypeId); }}
	}

	/// <summary>Field Creation Class for entity PortofolioEntity</summary>
	public partial class PortofolioFields
	{
		/// <summary>Creates a new PortofolioEntity.Cash field instance</summary>
		public static EntityField2 Cash { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PortofolioFieldIndex.Cash); }}
		/// <summary>Creates a new PortofolioEntity.CreateDate field instance</summary>
		public static EntityField2 CreateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PortofolioFieldIndex.CreateDate); }}
		/// <summary>Creates a new PortofolioEntity.PortofolioId field instance</summary>
		public static EntityField2 PortofolioId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PortofolioFieldIndex.PortofolioId); }}
		/// <summary>Creates a new PortofolioEntity.UpdateDate field instance</summary>
		public static EntityField2 UpdateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PortofolioFieldIndex.UpdateDate); }}
		/// <summary>Creates a new PortofolioEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PortofolioFieldIndex.UserId); }}
		/// <summary>Creates a new PortofolioEntity.Value field instance</summary>
		public static EntityField2 Value { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PortofolioFieldIndex.Value); }}
	}

	/// <summary>Field Creation Class for entity PortofolioItemEntity</summary>
	public partial class PortofolioItemFields
	{
		/// <summary>Creates a new PortofolioItemEntity.AverageValue field instance</summary>
		public static EntityField2 AverageValue { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PortofolioItemFieldIndex.AverageValue); }}
		/// <summary>Creates a new PortofolioItemEntity.CreateDate field instance</summary>
		public static EntityField2 CreateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PortofolioItemFieldIndex.CreateDate); }}
		/// <summary>Creates a new PortofolioItemEntity.Lot field instance</summary>
		public static EntityField2 Lot { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PortofolioItemFieldIndex.Lot); }}
		/// <summary>Creates a new PortofolioItemEntity.PortofolioId field instance</summary>
		public static EntityField2 PortofolioId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PortofolioItemFieldIndex.PortofolioId); }}
		/// <summary>Creates a new PortofolioItemEntity.PortofolioItemId field instance</summary>
		public static EntityField2 PortofolioItemId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PortofolioItemFieldIndex.PortofolioItemId); }}
		/// <summary>Creates a new PortofolioItemEntity.Shared field instance</summary>
		public static EntityField2 Shared { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PortofolioItemFieldIndex.Shared); }}
		/// <summary>Creates a new PortofolioItemEntity.StockId field instance</summary>
		public static EntityField2 StockId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PortofolioItemFieldIndex.StockId); }}
		/// <summary>Creates a new PortofolioItemEntity.TotalValue field instance</summary>
		public static EntityField2 TotalValue { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PortofolioItemFieldIndex.TotalValue); }}
		/// <summary>Creates a new PortofolioItemEntity.UpdateDate field instance</summary>
		public static EntityField2 UpdateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PortofolioItemFieldIndex.UpdateDate); }}
		/// <summary>Creates a new PortofolioItemEntity.Version field instance</summary>
		public static EntityField2 Version { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PortofolioItemFieldIndex.Version); }}
	}

	/// <summary>Field Creation Class for entity StockEntity</summary>
	public partial class StockFields
	{
		/// <summary>Creates a new StockEntity.Code field instance</summary>
		public static EntityField2 Code { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockFieldIndex.Code); }}
		/// <summary>Creates a new StockEntity.CreatedDate field instance</summary>
		public static EntityField2 CreatedDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockFieldIndex.CreatedDate); }}
		/// <summary>Creates a new StockEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockFieldIndex.IsActive); }}
		/// <summary>Creates a new StockEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockFieldIndex.Name); }}
		/// <summary>Creates a new StockEntity.ReleaseDate field instance</summary>
		public static EntityField2 ReleaseDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockFieldIndex.ReleaseDate); }}
		/// <summary>Creates a new StockEntity.StockId field instance</summary>
		public static EntityField2 StockId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockFieldIndex.StockId); }}
		/// <summary>Creates a new StockEntity.StockSectorId field instance</summary>
		public static EntityField2 StockSectorId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockFieldIndex.StockSectorId); }}
		/// <summary>Creates a new StockEntity.TotalShare field instance</summary>
		public static EntityField2 TotalShare { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockFieldIndex.TotalShare); }}
		/// <summary>Creates a new StockEntity.UpdateDate field instance</summary>
		public static EntityField2 UpdateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockFieldIndex.UpdateDate); }}
	}

	/// <summary>Field Creation Class for entity StockSectorEntity</summary>
	public partial class StockSectorFields
	{
		/// <summary>Creates a new StockSectorEntity.Code field instance</summary>
		public static EntityField2 Code { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockSectorFieldIndex.Code); }}
		/// <summary>Creates a new StockSectorEntity.CreateDate field instance</summary>
		public static EntityField2 CreateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockSectorFieldIndex.CreateDate); }}
		/// <summary>Creates a new StockSectorEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockSectorFieldIndex.IsActive); }}
		/// <summary>Creates a new StockSectorEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockSectorFieldIndex.Name); }}
		/// <summary>Creates a new StockSectorEntity.StockSectorId field instance</summary>
		public static EntityField2 StockSectorId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockSectorFieldIndex.StockSectorId); }}
		/// <summary>Creates a new StockSectorEntity.UpdateDate field instance</summary>
		public static EntityField2 UpdateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockSectorFieldIndex.UpdateDate); }}
	}

	/// <summary>Field Creation Class for entity SummaryEntity</summary>
	public partial class SummaryFields
	{
		/// <summary>Creates a new SummaryEntity.AdjustmentCurrentCash field instance</summary>
		public static EntityField2 AdjustmentCurrentCash { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.AdjustmentCurrentCash); }}
		/// <summary>Creates a new SummaryEntity.CapitalGain field instance</summary>
		public static EntityField2 CapitalGain { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.CapitalGain); }}
		/// <summary>Creates a new SummaryEntity.CapitalLoss field instance</summary>
		public static EntityField2 CapitalLoss { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.CapitalLoss); }}
		/// <summary>Creates a new SummaryEntity.CreateDate field instance</summary>
		public static EntityField2 CreateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.CreateDate); }}
		/// <summary>Creates a new SummaryEntity.CurrentCash field instance</summary>
		public static EntityField2 CurrentCash { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.CurrentCash); }}
		/// <summary>Creates a new SummaryEntity.Deviden field instance</summary>
		public static EntityField2 Deviden { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.Deviden); }}
		/// <summary>Creates a new SummaryEntity.LoanInterest field instance</summary>
		public static EntityField2 LoanInterest { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.LoanInterest); }}
		/// <summary>Creates a new SummaryEntity.MateraiFee field instance</summary>
		public static EntityField2 MateraiFee { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.MateraiFee); }}
		/// <summary>Creates a new SummaryEntity.SummaryDate field instance</summary>
		public static EntityField2 SummaryDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.SummaryDate); }}
		/// <summary>Creates a new SummaryEntity.SummaryId field instance</summary>
		public static EntityField2 SummaryId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.SummaryId); }}
		/// <summary>Creates a new SummaryEntity.TotalBuyNetAmount field instance</summary>
		public static EntityField2 TotalBuyNetAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.TotalBuyNetAmount); }}
		/// <summary>Creates a new SummaryEntity.TotalSellNetAmount field instance</summary>
		public static EntityField2 TotalSellNetAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.TotalSellNetAmount); }}
		/// <summary>Creates a new SummaryEntity.Transfer field instance</summary>
		public static EntityField2 Transfer { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.Transfer); }}
		/// <summary>Creates a new SummaryEntity.UpdateDate field instance</summary>
		public static EntityField2 UpdateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.UpdateDate); }}
		/// <summary>Creates a new SummaryEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.UserId); }}
		/// <summary>Creates a new SummaryEntity.Version field instance</summary>
		public static EntityField2 Version { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.Version); }}
		/// <summary>Creates a new SummaryEntity.Withdraw field instance</summary>
		public static EntityField2 Withdraw { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SummaryFieldIndex.Withdraw); }}
	}

	/// <summary>Field Creation Class for entity TransactionEntity</summary>
	public partial class TransactionFields
	{
		/// <summary>Creates a new TransactionEntity.BuyTransactionId field instance</summary>
		public static EntityField2 BuyTransactionId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.BuyTransactionId); }}
		/// <summary>Creates a new TransactionEntity.CancelDate field instance</summary>
		public static EntityField2 CancelDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.CancelDate); }}
		/// <summary>Creates a new TransactionEntity.CreateDate field instance</summary>
		public static EntityField2 CreateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.CreateDate); }}
		/// <summary>Creates a new TransactionEntity.GrossAmount field instance</summary>
		public static EntityField2 GrossAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.GrossAmount); }}
		/// <summary>Creates a new TransactionEntity.IsSellFirst field instance</summary>
		public static EntityField2 IsSellFirst { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.IsSellFirst); }}
		/// <summary>Creates a new TransactionEntity.Lot field instance</summary>
		public static EntityField2 Lot { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.Lot); }}
		/// <summary>Creates a new TransactionEntity.NetAmount field instance</summary>
		public static EntityField2 NetAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.NetAmount); }}
		/// <summary>Creates a new TransactionEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.Price); }}
		/// <summary>Creates a new TransactionEntity.SellTransactionId field instance</summary>
		public static EntityField2 SellTransactionId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.SellTransactionId); }}
		/// <summary>Creates a new TransactionEntity.Shared field instance</summary>
		public static EntityField2 Shared { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.Shared); }}
		/// <summary>Creates a new TransactionEntity.StockId field instance</summary>
		public static EntityField2 StockId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.StockId); }}
		/// <summary>Creates a new TransactionEntity.TransactionDate field instance</summary>
		public static EntityField2 TransactionDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.TransactionDate); }}
		/// <summary>Creates a new TransactionEntity.TransactionFee field instance</summary>
		public static EntityField2 TransactionFee { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.TransactionFee); }}
		/// <summary>Creates a new TransactionEntity.TransactionId field instance</summary>
		public static EntityField2 TransactionId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.TransactionId); }}
		/// <summary>Creates a new TransactionEntity.TransactionStatusId field instance</summary>
		public static EntityField2 TransactionStatusId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.TransactionStatusId); }}
		/// <summary>Creates a new TransactionEntity.TransactionTypeId field instance</summary>
		public static EntityField2 TransactionTypeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.TransactionTypeId); }}
		/// <summary>Creates a new TransactionEntity.UpdateDate field instance</summary>
		public static EntityField2 UpdateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.UpdateDate); }}
		/// <summary>Creates a new TransactionEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.UserId); }}
		/// <summary>Creates a new TransactionEntity.Version field instance</summary>
		public static EntityField2 Version { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionFieldIndex.Version); }}
	}

	/// <summary>Field Creation Class for entity TransactionStatusEntity</summary>
	public partial class TransactionStatusFields
	{
		/// <summary>Creates a new TransactionStatusEntity.Code field instance</summary>
		public static EntityField2 Code { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionStatusFieldIndex.Code); }}
		/// <summary>Creates a new TransactionStatusEntity.CreateDate field instance</summary>
		public static EntityField2 CreateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionStatusFieldIndex.CreateDate); }}
		/// <summary>Creates a new TransactionStatusEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionStatusFieldIndex.Name); }}
		/// <summary>Creates a new TransactionStatusEntity.TransactionStatusId field instance</summary>
		public static EntityField2 TransactionStatusId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionStatusFieldIndex.TransactionStatusId); }}
		/// <summary>Creates a new TransactionStatusEntity.Version field instance</summary>
		public static EntityField2 Version { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionStatusFieldIndex.Version); }}
	}

	/// <summary>Field Creation Class for entity TransactionTypeEntity</summary>
	public partial class TransactionTypeFields
	{
		/// <summary>Creates a new TransactionTypeEntity.Code field instance</summary>
		public static EntityField2 Code { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionTypeFieldIndex.Code); }}
		/// <summary>Creates a new TransactionTypeEntity.CreateDate field instance</summary>
		public static EntityField2 CreateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionTypeFieldIndex.CreateDate); }}
		/// <summary>Creates a new TransactionTypeEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionTypeFieldIndex.Name); }}
		/// <summary>Creates a new TransactionTypeEntity.TransactionTypeId field instance</summary>
		public static EntityField2 TransactionTypeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionTypeFieldIndex.TransactionTypeId); }}
		/// <summary>Creates a new TransactionTypeEntity.Version field instance</summary>
		public static EntityField2 Version { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TransactionTypeFieldIndex.Version); }}
	}

	/// <summary>Field Creation Class for entity UserEntity</summary>
	public partial class UserFields
	{
		/// <summary>Creates a new UserEntity.CreateDate field instance</summary>
		public static EntityField2 CreateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.CreateDate); }}
		/// <summary>Creates a new UserEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Name); }}
		/// <summary>Creates a new UserEntity.Password field instance</summary>
		public static EntityField2 Password { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Password); }}
		/// <summary>Creates a new UserEntity.UpdateDate field instance</summary>
		public static EntityField2 UpdateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.UpdateDate); }}
		/// <summary>Creates a new UserEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.UserId); }}
		/// <summary>Creates a new UserEntity.UserName field instance</summary>
		public static EntityField2 UserName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.UserName); }}
		/// <summary>Creates a new UserEntity.Version field instance</summary>
		public static EntityField2 Version { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Version); }}
	}
	

}