//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using Dummy.FactoryClasses;
using Dummy.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Dummy.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitConfigurationEntityInfo();
			InitOrderHistoryEntityInfo();
			InitOrderTypeEntityInfo();
			InitPortofolioEntityInfo();
			InitPortofolioItemEntityInfo();
			InitStockEntityInfo();
			InitStockSectorEntityInfo();
			InitSummaryEntityInfo();
			InitTransactionEntityInfo();
			InitTransactionStatusEntityInfo();
			InitTransactionTypeEntityInfo();
			InitUserEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits ConfigurationEntity's info objects</summary>
		private void InitConfigurationEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ConfigurationFieldIndex), "ConfigurationEntity");
			this.AddElementFieldInfo("ConfigurationEntity", "ConfigurationId", typeof(System.Int32), true, false, true, false,  (int)ConfigurationFieldIndex.ConfigurationId, 0, 0, 10);
			this.AddElementFieldInfo("ConfigurationEntity", "CreateDate", typeof(System.DateTime), false, false, false, false,  (int)ConfigurationFieldIndex.CreateDate, 0, 0, 7);
			this.AddElementFieldInfo("ConfigurationEntity", "Name", typeof(System.String), false, false, false, false,  (int)ConfigurationFieldIndex.Name, 100, 0, 0);
			this.AddElementFieldInfo("ConfigurationEntity", "UpdateDate", typeof(System.DateTime), false, false, false, false,  (int)ConfigurationFieldIndex.UpdateDate, 0, 0, 7);
			this.AddElementFieldInfo("ConfigurationEntity", "Value", typeof(System.String), false, false, false, false,  (int)ConfigurationFieldIndex.Value, 100, 0, 0);
			this.AddElementFieldInfo("ConfigurationEntity", "Version", typeof(System.Int32), false, false, false, false,  (int)ConfigurationFieldIndex.Version, 0, 0, 10);
		}

		/// <summary>Inits OrderHistoryEntity's info objects</summary>
		private void InitOrderHistoryEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(OrderHistoryFieldIndex), "OrderHistoryEntity");
			this.AddElementFieldInfo("OrderHistoryEntity", "Amount", typeof(System.Decimal), false, false, false, false,  (int)OrderHistoryFieldIndex.Amount, 0, 4, 19);
			this.AddElementFieldInfo("OrderHistoryEntity", "CancelDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrderHistoryFieldIndex.CancelDate, 0, 0, 7);
			this.AddElementFieldInfo("OrderHistoryEntity", "CreateDate", typeof(System.DateTime), false, false, false, false,  (int)OrderHistoryFieldIndex.CreateDate, 0, 0, 7);
			this.AddElementFieldInfo("OrderHistoryEntity", "OrderDate", typeof(System.DateTime), false, false, false, false,  (int)OrderHistoryFieldIndex.OrderDate, 0, 0, 7);
			this.AddElementFieldInfo("OrderHistoryEntity", "OrderHistoryId", typeof(System.Int64), true, false, true, false,  (int)OrderHistoryFieldIndex.OrderHistoryId, 0, 0, 19);
			this.AddElementFieldInfo("OrderHistoryEntity", "OrderTypeId", typeof(System.Int16), false, true, false, false,  (int)OrderHistoryFieldIndex.OrderTypeId, 0, 0, 5);
			this.AddElementFieldInfo("OrderHistoryEntity", "UpdateDate", typeof(System.DateTime), false, false, false, false,  (int)OrderHistoryFieldIndex.UpdateDate, 0, 0, 7);
		}

		/// <summary>Inits OrderTypeEntity's info objects</summary>
		private void InitOrderTypeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(OrderTypeFieldIndex), "OrderTypeEntity");
			this.AddElementFieldInfo("OrderTypeEntity", "Code", typeof(System.String), false, false, false, false,  (int)OrderTypeFieldIndex.Code, 50, 0, 0);
			this.AddElementFieldInfo("OrderTypeEntity", "CreateDate", typeof(System.DateTime), false, false, false, false,  (int)OrderTypeFieldIndex.CreateDate, 0, 0, 7);
			this.AddElementFieldInfo("OrderTypeEntity", "Name", typeof(System.String), false, false, false, false,  (int)OrderTypeFieldIndex.Name, 50, 0, 0);
			this.AddElementFieldInfo("OrderTypeEntity", "OrderTypeId", typeof(System.Int16), true, false, true, false,  (int)OrderTypeFieldIndex.OrderTypeId, 0, 0, 5);
		}

		/// <summary>Inits PortofolioEntity's info objects</summary>
		private void InitPortofolioEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(PortofolioFieldIndex), "PortofolioEntity");
			this.AddElementFieldInfo("PortofolioEntity", "Cash", typeof(System.Decimal), false, false, false, false,  (int)PortofolioFieldIndex.Cash, 0, 4, 19);
			this.AddElementFieldInfo("PortofolioEntity", "CreateDate", typeof(System.DateTime), false, false, false, false,  (int)PortofolioFieldIndex.CreateDate, 0, 0, 7);
			this.AddElementFieldInfo("PortofolioEntity", "PortofolioId", typeof(System.Int32), true, false, false, false,  (int)PortofolioFieldIndex.PortofolioId, 0, 0, 10);
			this.AddElementFieldInfo("PortofolioEntity", "UpdateDate", typeof(System.DateTime), false, false, false, false,  (int)PortofolioFieldIndex.UpdateDate, 0, 0, 7);
			this.AddElementFieldInfo("PortofolioEntity", "UserId", typeof(System.Int32), false, true, true, false,  (int)PortofolioFieldIndex.UserId, 0, 0, 10);
			this.AddElementFieldInfo("PortofolioEntity", "Value", typeof(System.Decimal), false, false, false, false,  (int)PortofolioFieldIndex.Value, 0, 4, 19);
		}

		/// <summary>Inits PortofolioItemEntity's info objects</summary>
		private void InitPortofolioItemEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(PortofolioItemFieldIndex), "PortofolioItemEntity");
			this.AddElementFieldInfo("PortofolioItemEntity", "AverageValue", typeof(System.Decimal), false, false, false, false,  (int)PortofolioItemFieldIndex.AverageValue, 0, 4, 19);
			this.AddElementFieldInfo("PortofolioItemEntity", "CreateDate", typeof(System.DateTime), false, false, false, false,  (int)PortofolioItemFieldIndex.CreateDate, 0, 0, 7);
			this.AddElementFieldInfo("PortofolioItemEntity", "Lot", typeof(System.Int64), false, false, false, false,  (int)PortofolioItemFieldIndex.Lot, 0, 0, 19);
			this.AddElementFieldInfo("PortofolioItemEntity", "PortofolioId", typeof(System.Int32), false, true, false, false,  (int)PortofolioItemFieldIndex.PortofolioId, 0, 0, 10);
			this.AddElementFieldInfo("PortofolioItemEntity", "PortofolioItemId", typeof(System.Int64), true, false, true, false,  (int)PortofolioItemFieldIndex.PortofolioItemId, 0, 0, 19);
			this.AddElementFieldInfo("PortofolioItemEntity", "Shared", typeof(System.Int64), false, false, false, false,  (int)PortofolioItemFieldIndex.Shared, 0, 0, 19);
			this.AddElementFieldInfo("PortofolioItemEntity", "StockId", typeof(System.Int32), false, true, false, false,  (int)PortofolioItemFieldIndex.StockId, 0, 0, 10);
			this.AddElementFieldInfo("PortofolioItemEntity", "TotalValue", typeof(System.Decimal), false, false, false, false,  (int)PortofolioItemFieldIndex.TotalValue, 0, 4, 19);
			this.AddElementFieldInfo("PortofolioItemEntity", "UpdateDate", typeof(System.DateTime), false, false, false, false,  (int)PortofolioItemFieldIndex.UpdateDate, 0, 0, 7);
			this.AddElementFieldInfo("PortofolioItemEntity", "Version", typeof(System.Int64), false, false, false, false,  (int)PortofolioItemFieldIndex.Version, 0, 0, 19);
		}

		/// <summary>Inits StockEntity's info objects</summary>
		private void InitStockEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(StockFieldIndex), "StockEntity");
			this.AddElementFieldInfo("StockEntity", "Code", typeof(System.String), false, false, false, false,  (int)StockFieldIndex.Code, 2147483647, 0, 0);
			this.AddElementFieldInfo("StockEntity", "CreatedDate", typeof(System.DateTime), false, false, false, false,  (int)StockFieldIndex.CreatedDate, 0, 0, 7);
			this.AddElementFieldInfo("StockEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)StockFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("StockEntity", "Name", typeof(System.String), false, false, false, false,  (int)StockFieldIndex.Name, 2147483647, 0, 0);
			this.AddElementFieldInfo("StockEntity", "ReleaseDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)StockFieldIndex.ReleaseDate, 0, 0, 0);
			this.AddElementFieldInfo("StockEntity", "StockId", typeof(System.Int32), true, false, true, false,  (int)StockFieldIndex.StockId, 0, 0, 10);
			this.AddElementFieldInfo("StockEntity", "StockSectorId", typeof(System.Int32), false, true, false, false,  (int)StockFieldIndex.StockSectorId, 0, 0, 10);
			this.AddElementFieldInfo("StockEntity", "TotalShare", typeof(Nullable<System.Int64>), false, false, false, true,  (int)StockFieldIndex.TotalShare, 0, 0, 19);
			this.AddElementFieldInfo("StockEntity", "UpdateDate", typeof(System.DateTime), false, false, false, false,  (int)StockFieldIndex.UpdateDate, 0, 0, 7);
		}

		/// <summary>Inits StockSectorEntity's info objects</summary>
		private void InitStockSectorEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(StockSectorFieldIndex), "StockSectorEntity");
			this.AddElementFieldInfo("StockSectorEntity", "Code", typeof(System.String), false, false, false, false,  (int)StockSectorFieldIndex.Code, 100, 0, 0);
			this.AddElementFieldInfo("StockSectorEntity", "CreateDate", typeof(System.DateTime), false, false, false, false,  (int)StockSectorFieldIndex.CreateDate, 0, 0, 7);
			this.AddElementFieldInfo("StockSectorEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)StockSectorFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("StockSectorEntity", "Name", typeof(System.String), false, false, false, false,  (int)StockSectorFieldIndex.Name, 500, 0, 0);
			this.AddElementFieldInfo("StockSectorEntity", "StockSectorId", typeof(System.Int32), true, false, true, false,  (int)StockSectorFieldIndex.StockSectorId, 0, 0, 10);
			this.AddElementFieldInfo("StockSectorEntity", "UpdateDate", typeof(System.DateTime), false, false, false, false,  (int)StockSectorFieldIndex.UpdateDate, 0, 0, 7);
		}

		/// <summary>Inits SummaryEntity's info objects</summary>
		private void InitSummaryEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(SummaryFieldIndex), "SummaryEntity");
			this.AddElementFieldInfo("SummaryEntity", "AdjustmentCurrentCash", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)SummaryFieldIndex.AdjustmentCurrentCash, 0, 4, 19);
			this.AddElementFieldInfo("SummaryEntity", "CapitalGain", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)SummaryFieldIndex.CapitalGain, 0, 4, 19);
			this.AddElementFieldInfo("SummaryEntity", "CapitalLoss", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)SummaryFieldIndex.CapitalLoss, 0, 4, 19);
			this.AddElementFieldInfo("SummaryEntity", "CreateDate", typeof(System.DateTime), false, false, false, false,  (int)SummaryFieldIndex.CreateDate, 0, 0, 7);
			this.AddElementFieldInfo("SummaryEntity", "CurrentCash", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)SummaryFieldIndex.CurrentCash, 0, 4, 19);
			this.AddElementFieldInfo("SummaryEntity", "Deviden", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)SummaryFieldIndex.Deviden, 0, 4, 19);
			this.AddElementFieldInfo("SummaryEntity", "LoanInterest", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)SummaryFieldIndex.LoanInterest, 0, 4, 19);
			this.AddElementFieldInfo("SummaryEntity", "MateraiFee", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)SummaryFieldIndex.MateraiFee, 0, 4, 19);
			this.AddElementFieldInfo("SummaryEntity", "SummaryDate", typeof(System.DateTime), false, false, false, false,  (int)SummaryFieldIndex.SummaryDate, 0, 0, 7);
			this.AddElementFieldInfo("SummaryEntity", "SummaryId", typeof(System.Int64), true, false, true, false,  (int)SummaryFieldIndex.SummaryId, 0, 0, 19);
			this.AddElementFieldInfo("SummaryEntity", "TotalBuyNetAmount", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)SummaryFieldIndex.TotalBuyNetAmount, 0, 4, 19);
			this.AddElementFieldInfo("SummaryEntity", "TotalSellNetAmount", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)SummaryFieldIndex.TotalSellNetAmount, 0, 4, 19);
			this.AddElementFieldInfo("SummaryEntity", "Transfer", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)SummaryFieldIndex.Transfer, 0, 4, 19);
			this.AddElementFieldInfo("SummaryEntity", "UpdateDate", typeof(System.DateTime), false, false, false, false,  (int)SummaryFieldIndex.UpdateDate, 0, 0, 7);
			this.AddElementFieldInfo("SummaryEntity", "UserId", typeof(System.Int32), false, true, false, false,  (int)SummaryFieldIndex.UserId, 0, 0, 10);
			this.AddElementFieldInfo("SummaryEntity", "Version", typeof(System.Int32), false, false, false, false,  (int)SummaryFieldIndex.Version, 0, 0, 10);
			this.AddElementFieldInfo("SummaryEntity", "Withdraw", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)SummaryFieldIndex.Withdraw, 0, 4, 19);
		}

		/// <summary>Inits TransactionEntity's info objects</summary>
		private void InitTransactionEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(TransactionFieldIndex), "TransactionEntity");
			this.AddElementFieldInfo("TransactionEntity", "BuyTransactionId", typeof(Nullable<System.Int64>), false, true, false, true,  (int)TransactionFieldIndex.BuyTransactionId, 0, 0, 19);
			this.AddElementFieldInfo("TransactionEntity", "CancelDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)TransactionFieldIndex.CancelDate, 0, 0, 7);
			this.AddElementFieldInfo("TransactionEntity", "CreateDate", typeof(System.DateTime), false, false, false, false,  (int)TransactionFieldIndex.CreateDate, 0, 0, 7);
			this.AddElementFieldInfo("TransactionEntity", "GrossAmount", typeof(System.String), false, false, false, false,  (int)TransactionFieldIndex.GrossAmount, 10, 0, 0);
			this.AddElementFieldInfo("TransactionEntity", "IsSellFirst", typeof(System.Boolean), false, false, false, false,  (int)TransactionFieldIndex.IsSellFirst, 0, 0, 0);
			this.AddElementFieldInfo("TransactionEntity", "Lot", typeof(System.Int64), false, false, false, false,  (int)TransactionFieldIndex.Lot, 0, 0, 19);
			this.AddElementFieldInfo("TransactionEntity", "NetAmount", typeof(System.Decimal), false, false, false, false,  (int)TransactionFieldIndex.NetAmount, 0, 4, 19);
			this.AddElementFieldInfo("TransactionEntity", "Price", typeof(System.Decimal), false, false, false, false,  (int)TransactionFieldIndex.Price, 0, 4, 19);
			this.AddElementFieldInfo("TransactionEntity", "SellTransactionId", typeof(Nullable<System.Int64>), false, true, false, true,  (int)TransactionFieldIndex.SellTransactionId, 0, 0, 19);
			this.AddElementFieldInfo("TransactionEntity", "Shared", typeof(System.Int64), false, false, false, false,  (int)TransactionFieldIndex.Shared, 0, 0, 19);
			this.AddElementFieldInfo("TransactionEntity", "StockId", typeof(System.Int32), false, true, false, false,  (int)TransactionFieldIndex.StockId, 0, 0, 10);
			this.AddElementFieldInfo("TransactionEntity", "TransactionDate", typeof(System.DateTime), false, false, false, false,  (int)TransactionFieldIndex.TransactionDate, 0, 0, 7);
			this.AddElementFieldInfo("TransactionEntity", "TransactionFee", typeof(System.Decimal), false, false, false, false,  (int)TransactionFieldIndex.TransactionFee, 0, 4, 19);
			this.AddElementFieldInfo("TransactionEntity", "TransactionId", typeof(System.Int64), true, false, true, false,  (int)TransactionFieldIndex.TransactionId, 0, 0, 19);
			this.AddElementFieldInfo("TransactionEntity", "TransactionStatusId", typeof(System.Int16), false, true, false, false,  (int)TransactionFieldIndex.TransactionStatusId, 0, 0, 5);
			this.AddElementFieldInfo("TransactionEntity", "TransactionTypeId", typeof(System.Int16), false, true, false, false,  (int)TransactionFieldIndex.TransactionTypeId, 0, 0, 5);
			this.AddElementFieldInfo("TransactionEntity", "UpdateDate", typeof(System.DateTime), false, false, false, false,  (int)TransactionFieldIndex.UpdateDate, 0, 0, 7);
			this.AddElementFieldInfo("TransactionEntity", "UserId", typeof(System.Int32), false, true, false, false,  (int)TransactionFieldIndex.UserId, 0, 0, 10);
			this.AddElementFieldInfo("TransactionEntity", "Version", typeof(System.Int64), false, false, false, false,  (int)TransactionFieldIndex.Version, 0, 0, 19);
		}

		/// <summary>Inits TransactionStatusEntity's info objects</summary>
		private void InitTransactionStatusEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(TransactionStatusFieldIndex), "TransactionStatusEntity");
			this.AddElementFieldInfo("TransactionStatusEntity", "Code", typeof(System.String), false, false, false, false,  (int)TransactionStatusFieldIndex.Code, 50, 0, 0);
			this.AddElementFieldInfo("TransactionStatusEntity", "CreateDate", typeof(System.DateTime), false, false, false, false,  (int)TransactionStatusFieldIndex.CreateDate, 0, 0, 7);
			this.AddElementFieldInfo("TransactionStatusEntity", "Name", typeof(System.String), false, false, false, false,  (int)TransactionStatusFieldIndex.Name, 50, 0, 0);
			this.AddElementFieldInfo("TransactionStatusEntity", "TransactionStatusId", typeof(System.Int16), true, false, true, false,  (int)TransactionStatusFieldIndex.TransactionStatusId, 0, 0, 5);
			this.AddElementFieldInfo("TransactionStatusEntity", "Version", typeof(System.Int32), false, false, false, false,  (int)TransactionStatusFieldIndex.Version, 0, 0, 10);
		}

		/// <summary>Inits TransactionTypeEntity's info objects</summary>
		private void InitTransactionTypeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(TransactionTypeFieldIndex), "TransactionTypeEntity");
			this.AddElementFieldInfo("TransactionTypeEntity", "Code", typeof(System.String), false, false, false, false,  (int)TransactionTypeFieldIndex.Code, 50, 0, 0);
			this.AddElementFieldInfo("TransactionTypeEntity", "CreateDate", typeof(System.DateTime), false, false, false, false,  (int)TransactionTypeFieldIndex.CreateDate, 0, 0, 7);
			this.AddElementFieldInfo("TransactionTypeEntity", "Name", typeof(System.String), false, false, false, false,  (int)TransactionTypeFieldIndex.Name, 50, 0, 0);
			this.AddElementFieldInfo("TransactionTypeEntity", "TransactionTypeId", typeof(System.Int16), true, false, true, false,  (int)TransactionTypeFieldIndex.TransactionTypeId, 0, 0, 5);
			this.AddElementFieldInfo("TransactionTypeEntity", "Version", typeof(System.Int32), false, false, false, false,  (int)TransactionTypeFieldIndex.Version, 0, 0, 10);
		}

		/// <summary>Inits UserEntity's info objects</summary>
		private void InitUserEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(UserFieldIndex), "UserEntity");
			this.AddElementFieldInfo("UserEntity", "CreateDate", typeof(System.DateTime), false, false, false, false,  (int)UserFieldIndex.CreateDate, 0, 0, 7);
			this.AddElementFieldInfo("UserEntity", "Name", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Name, 200, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Password", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Password, 200, 0, 0);
			this.AddElementFieldInfo("UserEntity", "UpdateDate", typeof(System.DateTime), false, false, false, false,  (int)UserFieldIndex.UpdateDate, 0, 0, 7);
			this.AddElementFieldInfo("UserEntity", "UserId", typeof(System.Int32), true, false, true, false,  (int)UserFieldIndex.UserId, 0, 0, 10);
			this.AddElementFieldInfo("UserEntity", "UserName", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.UserName, 200, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Version", typeof(System.Int64), false, false, false, false,  (int)UserFieldIndex.Version, 0, 0, 19);
		}
	}
}